# Site settings
title: Learning Notes
description: "Programming guides and learning notes, web scraping, frontend development, handheld gaming, etc."
baseurl: "/learning-notes" # the subpath of your site, e.g. /blog/
url: "https://dev-chenxing.github.io" # the base hostname & protocol for your site
enforce_ssl: dev-chenxing.github.io
cover: "/img/social-preview.png"

author:
  fullname: chen.xing
  github: dev-chenxing

# Syntax highlighting
highlightstyle: 'xcode'
styles: [default, github, xcode]

# Handling Reading
exclude: ["README.md", "venv"]

# Build settings
markdown: kramdown
highlighter: rogue

